--
-- PostgreSQL database dump
--

\restrict 3JjW13JhINDdX1ttTayror2gdqcyyrNpfhphcUJTGVR9ac36YoqEkyh5kHYfOLd

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(10) NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, role) FROM stdin;
1	pbkdf2_sha256$1000000$dTIkRCrFcU762p3yeS2yXC$3q2rUI6AVK91PI+orceEbdPuI5EiSYJ/VMCIetzS6ps=	\N	t			t	t	2025-11-06 14:14:59.819289+01	aitorpuyprog@gmail.com	admin
3	pbkdf2_sha256$1000000$ViQXxjwvES24C4HWVfGaz0$xtvABndHZrkQI30l2KciS/7k+ngNjVQ+0VwTUp6p5Bc=	\N	f			f	t	2025-11-06 22:53:23.502738+01	bbb@bbb.bbb	user
2	pbkdf2_sha256$1000000$L81Z6zJpfOPUFMjGu0H6VF$TM90f+vuoWRNnpeK/D9UExMnC0LKzlvSGGvlQHlWxbs=	\N	f			f	t	2025-11-06 22:40:04.299232+01	aaa@aaa.aaa	user
4	pbkdf2_sha256$1000000$y67oZcEUrR1fOJ4OyvSG3v$IotdT4Cipm1nCBeHBSLiBdyq+LmLonrWJ+45m235wb0=	\N	f			f	t	2025-11-09 08:25:56.891448+01	ccc@ccc.ccc	user
\.


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 4, true);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict 3JjW13JhINDdX1ttTayror2gdqcyyrNpfhphcUJTGVR9ac36YoqEkyh5kHYfOLd

