# Generated by Django 5.0.6 on 2026-01-07 12:18

import django.db.models.deletion
from django.db import migrations, models


def associate_users_to_primary_company(apps, schema_editor):
    """Asociar todos los usuarios existentes a la empresa primary"""
    User = apps.get_model('accounts', 'User')
    Company = apps.get_model('companies', 'Company')
    
    # Buscar empresa primary o crear una si no existe
    try:
        primary_company = Company.objects.get(is_primary=True)
    except Company.DoesNotExist:
        # Si no existe empresa primary, usar la primera disponible o crear una
        primary_company = Company.objects.first()
        if not primary_company:
            primary_company = Company.objects.create(name="Empresa Principal", is_primary=True)
        else:
            # Marcar como primary si no lo está
            primary_company.is_primary = True
            primary_company.save()
    
    # Asociar todos los usuarios existentes a la empresa primary
    User.objects.filter(codigo_empresa__isnull=True).update(codigo_empresa=primary_company)


def reverse_associate_users(apps, schema_editor):
    """Función reversa: no hace nada ya que eliminamos el campo"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('companies', '0003_set_primary_company'),
    ]

    operations = [
        # Paso 1: Agregar el campo como nullable
        migrations.AddField(
            model_name='user',
            name='codigo_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='companies.company', verbose_name='Código Empresa'),
        ),
        # Paso 2: Asociar usuarios existentes a empresa primary
        migrations.RunPython(associate_users_to_primary_company, reverse_associate_users),
        # Paso 3: Hacer el campo no-nullable
        migrations.AlterField(
            model_name='user',
            name='codigo_empresa',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='companies.company', verbose_name='Código Empresa'),
        ),
    ]
