# Generated by Django 5.0.6 on 2026-01-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
    ]
